# GENERAL
DIRPATH = "yolov5/runs/detect/exp"

# DETECTION
NN_TYPE  = "yolov5s.pt"
CONF_THR = 0.8

# EMAIL
SUBJECT        = "HomeSurv"
SENDER_EMAIL   = "INSERT SENDER E-MAIL HERE"
RECEIVER_EMAIL = "INSERT RECEIVER E-MAIL HERE"
APP_PASSWORD   = "INSERT APP PASSWORD HERE"
